/**
 * Aliyun CosyVoice 音色列表数据
 * 包含所有模型支持的音色及其特性
 */

export interface VoiceInfo {
	/** 音色名称 */
	name: string;
	/** voice 参数值 */
	voice: string;
	/** 音色描述 */
	description: string;
	/** 是否支持 SSML */
	supportsSSML: boolean;
	/** 是否支持 Instruct 指令 */
	supportsInstruct: boolean;
	/** 适用场景 */
	scenario?: string;
	/** 年龄段 */
	age?: string;
	/** 语言 */
	language: string;
}

export interface ModelVoiceList {
	[model: string]: VoiceInfo[];
}

/**
 * CosyVoice 音色列表
 * 数据来源: https://help.aliyun.com/zh/model-studio/cosyvoice-voice-list
 */
export const VOICE_LIST: ModelVoiceList = {
	'cosyvoice-v3-flash': [
		{
			name: '龙安洋',
			voice: 'longanyang',
			description: '阳光大男孩',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '社交陪伴',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙安欢',
			voice: 'longanhuan',
			description: '欢脱元气女',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '社交陪伴',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙呼呼',
			voice: 'longhuhu_v3',
			description: '天真烂漫女童',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '童声',
			age: '6-10岁',
			language: '中文、英文',
		},
		{
			name: '龙应沐',
			voice: 'longyingmu_v3',
			description: '优雅知性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '电话助手',
			age: '25-30岁',
			language: '中文、英文',
		},
		{
			name: '龙应笑',
			voice: 'longyingxiao_v3',
			description: '清甜推销女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '电话销售',
			age: '20-25岁',
			language: '中文、英文',
		},
		{
			name: '龙应询',
			voice: 'longyingxun_v3',
			description: '年轻青涩男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '电话客服',
			age: '20-25岁',
			language: '中文、英文',
		},
		{
			name: '龙应桃',
			voice: 'longyingtao_v3',
			description: '温柔淡定女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			age: '25-30岁',
			language: '中文、英文',
		},
		{
			name: '龙安昀',
			voice: 'longanyun_v3',
			description: '居家暖男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			age: '30-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安温',
			voice: 'longanwen_v3',
			description: '优雅知性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安莉',
			voice: 'longanli_v3',
			description: '利落从容女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安朗',
			voice: 'longanlang_v3',
			description: '清爽利落男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			age: '20-25岁',
			language: '中文、英文',
		},
		{
			name: '龙安智',
			voice: 'longanzhi_v3',
			description: '睿智轻熟男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '陪伴闲聊',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安灵',
			voice: 'longanling_v3',
			description: '思维灵动女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '陪伴闲聊',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙安雅',
			voice: 'longanya_v3',
			description: '高雅气质女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '陪伴闲聊',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安亲',
			voice: 'longanqin_v3',
			description: '亲和活泼女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '陪伴闲聊',
			age: '20-25岁',
			language: '中文、英文',
		},
		{
			name: '龙婉君',
			voice: 'longwanjun_v3',
			description: '细腻柔声女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙逸尘',
			voice: 'longyichen_v3',
			description: '洒脱活力男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙老伯',
			voice: 'longlaobo_v3',
			description: '沧桑岁月爷',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			age: '60岁以上',
			language: '中文、英文',
		},
		{
			name: '龙老姨',
			voice: 'longlaoyi_v3',
			description: '烟火从容阿姨',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			age: '60岁以上',
			language: '中文、英文',
		},
		{
			name: '龙机器',
			voice: 'longjiqi_v3',
			description: '呆萌机器人',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙猴哥',
			voice: 'longhouge_v3',
			description: '经典猴哥',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '20-25岁',
			language: '中文、英文',
		},
		{
			name: '龙黛玉',
			voice: 'longdaiyu_v3',
			description: '娇率才女音',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '15-25岁',
			language: '中文、英文',
		},
		{
			name: '龙安粤',
			voice: 'longanyue_v3',
			description: '欢脱粤语男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙陕哥',
			voice: 'longshange_v3',
			description: '原味陕北男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '25-35岁',
			language: '中文、英文',
		},
		{
			name: '龙安闽',
			voice: 'longanmin_v3',
			description: '清纯萝莉女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			age: '18-25岁',
			language: '中文、英文',
		},
		{
			name: '龙安宣',
			voice: 'longanxuan_v3',
			description: '经典直播女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '直播带货',
			age: '30-40岁',
			language: '中文、英文',
		},
		{
			name: 'Bella3.0',
			voice: 'loongbella_v3',
			description: '精准干练女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			age: '25-30岁',
			language: '中文、英文',
		},
	],

	'cosyvoice-v3-plus': [
		{
			name: '龙安洋',
			voice: 'longanyang',
			description: '阳光大男孩',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '社交陪伴',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙安欢',
			voice: 'longanhuan',
			description: '欢脱元气女',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '社交陪伴',
			age: '20-30岁',
			language: '中文、英文',
		},
		{
			name: '龙呼呼',
			voice: 'longhuhu_v3',
			description: '天真烂漫女童',
			supportsSSML: true,
			supportsInstruct: true,
			scenario: '童声',
			age: '6-10岁',
			language: '中文、英文',
		},
	],

	'cosyvoice-v2': [
		{
			name: '龙应笑',
			voice: 'longyingxiao',
			description: '清甜推销女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '电话销售',
			language: '中文、英文',
		},
		{
			name: '龙机器',
			voice: 'longjiqi',
			description: '呆萌机器人',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙猴哥',
			voice: 'longhouge',
			description: '经典猴哥',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙机心',
			voice: 'longjixin',
			description: '毒舌心机女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙安粤',
			voice: 'longanyue',
			description: '欢脱粤语男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙陕哥',
			voice: 'longshange',
			description: '原味陕北男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙安敏',
			voice: 'longanmin',
			description: '甜美闽南女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙黛玉',
			voice: 'longdaiyu',
			description: '娇率才女音',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙高僧',
			voice: 'longgaoseng',
			description: '得道高僧音',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '短视频配音',
			language: '中文、英文',
		},
		{
			name: '龙安莉',
			voice: 'longanli',
			description: '利落从容女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙安朗',
			voice: 'longanlang',
			description: '清爽利落男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙安温',
			voice: 'longanwen',
			description: '优雅知性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙安昀',
			voice: 'longanyun',
			description: '居家暖男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: 'YUMI',
			voice: 'longyumi_v2',
			description: '正经青年女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙小淳',
			voice: 'longxiaochun_v2',
			description: '知性积极女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙小夏',
			voice: 'longxiaoxia_v2',
			description: '沉稳权威女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '语音助手',
			language: '中文、英文',
		},
		{
			name: '龙逸尘',
			voice: 'longyichen',
			description: '洒脱活力男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙婉君',
			voice: 'longwanjun',
			description: '细腻柔声女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙老伯',
			voice: 'longlaobo',
			description: '沧桑岁月爷',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙老姨',
			voice: 'longlaoyi',
			description: '烟火从容阿姨',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙白芷',
			voice: 'longbaizhi',
			description: '睿气旁白女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙三叔',
			voice: 'longsanshu',
			description: '沉稳质感男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙修',
			voice: 'longxiu_v2',
			description: '博才说书男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙妙',
			voice: 'longmiao_v2',
			description: '抑扬顿挫女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙悦',
			voice: 'longyue_v2',
			description: '温暖磁性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙楠',
			voice: 'longnan_v2',
			description: '睿智青年男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙媛',
			voice: 'longyuan_v2',
			description: '温暖治愈女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '有声书',
			language: '中文、英文',
		},
		{
			name: '龙安亲',
			voice: 'longanqin',
			description: '亲和活泼女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙安雅',
			voice: 'longanya',
			description: '高雅气质女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙安朔',
			voice: 'longanshuo',
			description: '干净清爽男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙安灵',
			voice: 'longanling',
			description: '思维灵动女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙安智',
			voice: 'longanzhi',
			description: '睿智轻熟男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙安柔',
			voice: 'longanrou',
			description: '温柔闺蜜女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙嫱',
			voice: 'longqiang_v2',
			description: '浪漫风情女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙寒',
			voice: 'longhan_v2',
			description: '温暖痴情男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙星',
			voice: 'longxing_v2',
			description: '温婉邻家女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙华',
			voice: 'longhua_v2',
			description: '元气甜美女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙婉',
			voice: 'longwan_v2',
			description: '积极知性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙橙',
			voice: 'longcheng_v2',
			description: '智慧青年男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙菲菲',
			voice: 'longfeifei_v2',
			description: '甜美娇气女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙小诚',
			voice: 'longxiaocheng_v2',
			description: '磁性低音男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙哲',
			voice: 'longzhe_v2',
			description: '呆板大暖男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙颜',
			voice: 'longyan_v2',
			description: '温暖春风女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙天',
			voice: 'longtian_v2',
			description: '磁性理智男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙泽',
			voice: 'longze_v2',
			description: '温暖元气男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙邵',
			voice: 'longshao_v2',
			description: '积极向上男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙浩',
			voice: 'longhao_v2',
			description: '多情忧郁男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙深',
			voice: 'kabuleshen_v2',
			description: '实力歌手男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '社交陪伴',
			language: '中文、英文',
		},
		{
			name: '龙呼呼',
			voice: 'longhuhu',
			description: '天真烂漫女童',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '童声',
			language: '中文、英文',
		},
		{
			name: '龙安培',
			voice: 'longanpei',
			description: '青少年教师女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '教育培训',
			language: '中文、英文',
		},
		{
			name: '龙汪汪',
			voice: 'longwangwang',
			description: '台湾少年音',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '儿童陪伴',
			language: '中文、英文',
		},
		{
			name: '龙泡泡',
			voice: 'longpaopao',
			description: '飞天泡泡音',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '儿童陪伴',
			language: '中文、英文',
		},
		{
			name: '龙闪闪',
			voice: 'longshanshan',
			description: '戏剧化童声',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '儿童有声书',
			language: '中文、英文',
		},
		{
			name: '龙牛牛',
			voice: 'longniuniu',
			description: '阳光男童声',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '儿童有声书',
			language: '中文、英文',
		},
		{
			name: '龙应沐',
			voice: 'longyingmu',
			description: '优雅知性女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应询',
			voice: 'longyingxun',
			description: '年轻青涩男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应催',
			voice: 'longyingcui',
			description: '严肃催收男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应答',
			voice: 'longyingda',
			description: '开朗高音女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应静',
			voice: 'longyingjing',
			description: '低调冷静女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应严',
			voice: 'longyingyan',
			description: '义正严辞女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应甜',
			voice: 'longyingtian',
			description: '温柔甜美女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应冰',
			voice: 'longyingbing',
			description: '尖锐强势女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应桃',
			voice: 'longyingtao',
			description: '温柔淡定女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙应聆',
			voice: 'longyingling',
			description: '温和共情女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '客服',
			language: '中文、英文',
		},
		{
			name: '龙安燃',
			voice: 'longanran',
			description: '活泼质感女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '直播带货',
			language: '中文、英文',
		},
		{
			name: '龙安宣',
			voice: 'longanxuan',
			description: '经典直播女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '直播带货',
			language: '中文、英文',
		},
		{
			name: '龙安冲',
			voice: 'longanchong',
			description: '激情推销男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '直播带货',
			language: '中文、英文',
		},
		{
			name: '龙安萍',
			voice: 'longanping',
			description: '高亢直播女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '直播带货',
			language: '中文、英文',
		},
		{
			name: '龙杰力豆',
			voice: 'longjielidou_v2',
			description: '阳光顽皮男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '童声',
			language: '中文、英文',
		},
		{
			name: '龙铃',
			voice: 'longling_v2',
			description: '稚气呆板女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '童声',
			language: '中文、英文',
		},
		{
			name: '龙可',
			voice: 'longke_v2',
			description: '懵懂乖乖女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '童声',
			language: '中文、英文',
		},
		{
			name: '龙仙',
			voice: 'longxian_v2',
			description: '豪放可爱女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '童声',
			language: '中文、英文',
		},
		{
			name: '龙老铁',
			voice: 'longlaotie_v2',
			description: '东北直率男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '方言',
			language: '中（东北）、英',
		},
		{
			name: '龙嘉怡',
			voice: 'longjiayi_v2',
			description: '知性粤语女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '方言',
			language: '中（粤语）、英',
		},
		{
			name: '龙桃',
			voice: 'longtao_v2',
			description: '积极粤语女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '方言',
			language: '中（粤语）、英',
		},
		{
			name: '龙飞',
			voice: 'longfei_v2',
			description: '热血磁性男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '诗词朗诵',
			language: '中文、英文',
		},
		{
			name: '李白',
			voice: 'libai_v2',
			description: '古代诗仙男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '诗词朗诵',
			language: '中文、英文',
		},
		{
			name: '龙津',
			voice: 'longjin_v2',
			description: '优雅温润男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '诗词朗诵',
			language: '中文、英文',
		},
		{
			name: '龙书',
			voice: 'longshu_v2',
			description: '沉稳青年男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: 'Bella2.0',
			voice: 'loongbella_v2',
			description: '精准干练女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: '龙硕',
			voice: 'longshuo_v2',
			description: '博才干练男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: '龙小白',
			voice: 'longxiaobai_v2',
			description: '沉稳播报女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: '龙婧',
			voice: 'longjing_v2',
			description: '典型播音女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: 'loongstella',
			voice: 'loongstella_v2',
			description: '飒爽利落女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '新闻播报',
			language: '中文、英文',
		},
		{
			name: 'loongyuuna',
			voice: 'loongyuuna_v2',
			description: '元气霓虹女',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '日语',
		},
		{
			name: 'loongyuuma',
			voice: 'loongyuuma_v2',
			description: '干练霓虹男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '日语',
		},
		{
			name: 'loongjihun',
			voice: 'loongjihun_v2',
			description: '阳光韩国男',
			supportsSSML: true,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '韩语',
		},
		{
			name: 'loongeva',
			voice: 'loongeva_v2',
			description: '知性英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongbrian',
			voice: 'loongbrian_v2',
			description: '沉稳英文男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongluna',
			voice: 'loongluna_v2',
			description: '英式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongluca',
			voice: 'loongluca_v2',
			description: '英式英文男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongemily',
			voice: 'loongemily_v2',
			description: '英式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongeric',
			voice: 'loongeric_v2',
			description: '英式英文男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '英式英文',
		},
		{
			name: 'loongabby',
			voice: 'loongabby_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongannie',
			voice: 'loongannie_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongandy',
			voice: 'loongandy_v2',
			description: '美式英文男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongava',
			voice: 'loongava_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongbeth',
			voice: 'loongbeth_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongbetty',
			voice: 'loongbetty_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongcindy',
			voice: 'loongcindy_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongcally',
			voice: 'loongcally_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongdavid',
			voice: 'loongdavid_v2',
			description: '美式英文男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongdonna',
			voice: 'loongdonna_v2',
			description: '美式英文女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '美式英文',
		},
		{
			name: 'loongkyong',
			voice: 'loongkyong_v2',
			description: '韩语女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '韩语',
		},
		{
			name: 'loongtomoka',
			voice: 'loongtomoka_v2',
			description: '日语女',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '日语',
		},
		{
			name: 'loongtomoya',
			voice: 'loongtomoya_v2',
			description: '日语男',
			supportsSSML: false,
			supportsInstruct: false,
			scenario: '出海营销',
			language: '日语',
		},
	],

	'cosyvoice-v1': [
		{
			name: '龙婉',
			voice: 'longwan',
			description: '语音助手、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙橙',
			voice: 'longcheng',
			description: '语音助手、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙华',
			voice: 'longhua',
			description: '语音助手、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙小淳',
			voice: 'longxiaochun',
			description: '语音助手、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文、英文',
		},
		{
			name: '龙小夏',
			voice: 'longxiaoxia',
			description: '语音助手、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙小诚',
			voice: 'longxiaocheng',
			description: '语音助手、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文、英文',
		},
		{
			name: '龙小白',
			voice: 'longxiaobai',
			description: '聊天数字人、有声书、语音助手',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙老铁',
			voice: 'longlaotie',
			description: '新闻播报、有声书、语音助手、直播带货、导航播报',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文东北口音',
		},
		{
			name: '龙书',
			voice: 'longshu',
			description: '有声书、语音助手、导航播报、新闻播报、智能客服',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙硕',
			voice: 'longshuo',
			description: '语音助手、导航播报、新闻播报、客服催收',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙婧',
			voice: 'longjing',
			description: '语音助手、导航播报、新闻播报、客服催收',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙妙',
			voice: 'longmiao',
			description: '客服催收、导航播报、有声书、语音助手',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙悦',
			voice: 'longyue',
			description: '语音助手、诗词朗诵、有声书朗读、导航播报、新闻播报、客服催收',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙媛',
			voice: 'longyuan',
			description: '有声书、语音助手、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙飞',
			voice: 'longfei',
			description: '会议播报、新闻播报、有声书',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙杰力豆',
			voice: 'longjielidou',
			description: '新闻播报、有声书、聊天助手',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文、英文',
		},
		{
			name: '龙彤',
			voice: 'longtong',
			description: '有声书、导航播报、聊天数字人',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: '龙祥',
			voice: 'longxiang',
			description: '新闻播报、有声书、导航播报',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
		{
			name: 'Stella',
			voice: 'loongstella',
			description: '有声书、语音助手、直播带货、导航播报、客服催收',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文、英文',
		},
		{
			name: 'Bella',
			voice: 'loongbella',
			description: '语音助手、客服催收、新闻播报、导航播报',
			supportsSSML: false,
			supportsInstruct: false,
			language: '中文',
		},
	],
};

/**
 * 根据模型获取音色列表
 */
export function getVoicesByModel(model: string): VoiceInfo[] {
	return VOICE_LIST[model] || [];
}

/**
 * 获取所有支持的模型
 */
export function getSupportedModels(): string[] {
	return Object.keys(VOICE_LIST);
}

/**
 * 根据模型和 voice 参数值获取音色信息
 */
export function getVoiceInfo(model: string, voice: string): VoiceInfo | undefined {
	const voices = VOICE_LIST[model];
	if (!voices) return undefined;
	return voices.find((v) => v.voice === voice);
}
